### ISSUE TITLE
Zen background color should show through

### ISSUE THREAD

**Issue by Erudition** [Erudition/zen-sidebery-mod#2]
Currently, Sidebery's CSS editor needs to be used to add transparency for visual integration with Zen, e.g.

```css
:root {background-color: transparent;}

#root.root {
	--frame-bg: transparent;
	--toolbar-bg: transparent;
}
```

I will have this injected into Sidebery by default (can still override in CSS editor) so this is not needed.
