### ISSUE TITLE
Cursor should be grabbing while dragging

### ISSUE THREAD

**Issue by Erudition** [Erudition/zen-sidebery-mod#3]
This doesn't happen (for me) by default in sidebery, but as an enhancement, `cursor:grabbing` should be set when dragging tabs, for clarity.

**Comment by Erudition** [comment]
Haven't yet figured out how to get it to stick. This only works for a few tiny areas, then the cursor is back to normal:

```css
    #root.root[data-drag="true"], #root.root[data-drag="true"] .AnimatedTabList *, #root.root[data-drag="true"] .Tab, #root.root[data-drag="true"] .drag_image, #root.root[data-drag="true"] .pointer {
        cursor: grabbing !important;
    }
```
